/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSettingsRouteImport } from './routes/user/settings'
import { Route as CChatIdRouteImport } from './routes/c/$chatId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiSummarizerRouteImport } from './routes/api/summarizer'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiProtectRouteImport } from './routes/api/protect'
import { Route as ApiIndexerRouteImport } from './routes/api/indexer'
import { Route as ApiIngestSourceRouteImport } from './routes/api/ingest/$source'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizerRoute = ApiSummarizerRouteImport.update({
  id: '/api/summarizer',
  path: '/api/summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtectRoute = ApiProtectRouteImport.update({
  id: '/api/protect',
  path: '/api/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexerRoute = ApiIndexerRouteImport.update({
  id: '/api/indexer',
  path: '/api/indexer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestSourceRoute = ApiIngestSourceRouteImport.update({
  id: '/api/ingest/$source',
  path: '/api/ingest/$source',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/indexer': typeof ApiIndexerRoute
  '/api/protect': typeof ApiProtectRoute
  '/api/query': typeof ApiQueryRoute
  '/api/summarizer': typeof ApiSummarizerRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/c/$chatId': typeof CChatIdRoute
  '/user/settings': typeof UserSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$source': typeof ApiIngestSourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/indexer': typeof ApiIndexerRoute
  '/api/protect': typeof ApiProtectRoute
  '/api/query': typeof ApiQueryRoute
  '/api/summarizer': typeof ApiSummarizerRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/c/$chatId': typeof CChatIdRoute
  '/user/settings': typeof UserSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$source': typeof ApiIngestSourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/indexer': typeof ApiIndexerRoute
  '/api/protect': typeof ApiProtectRoute
  '/api/query': typeof ApiQueryRoute
  '/api/summarizer': typeof ApiSummarizerRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/c/$chatId': typeof CChatIdRoute
  '/user/settings': typeof UserSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ingest/$source': typeof ApiIngestSourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/indexer'
    | '/api/protect'
    | '/api/query'
    | '/api/summarizer'
    | '/auth/login'
    | '/auth/register'
    | '/c/$chatId'
    | '/user/settings'
    | '/api/auth/$'
    | '/api/ingest/$source'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/indexer'
    | '/api/protect'
    | '/api/query'
    | '/api/summarizer'
    | '/auth/login'
    | '/auth/register'
    | '/c/$chatId'
    | '/user/settings'
    | '/api/auth/$'
    | '/api/ingest/$source'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/indexer'
    | '/api/protect'
    | '/api/query'
    | '/api/summarizer'
    | '/auth/login'
    | '/auth/register'
    | '/c/$chatId'
    | '/user/settings'
    | '/api/auth/$'
    | '/api/ingest/$source'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiIndexerRoute: typeof ApiIndexerRoute
  ApiProtectRoute: typeof ApiProtectRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSummarizerRoute: typeof ApiSummarizerRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CChatIdRoute: typeof CChatIdRoute
  UserSettingsRoute: typeof UserSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIngestSourceRoute: typeof ApiIngestSourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarizer': {
      id: '/api/summarizer'
      path: '/api/summarizer'
      fullPath: '/api/summarizer'
      preLoaderRoute: typeof ApiSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protect': {
      id: '/api/protect'
      path: '/api/protect'
      fullPath: '/api/protect'
      preLoaderRoute: typeof ApiProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indexer': {
      id: '/api/indexer'
      path: '/api/indexer'
      fullPath: '/api/indexer'
      preLoaderRoute: typeof ApiIndexerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/$source': {
      id: '/api/ingest/$source'
      path: '/api/ingest/$source'
      fullPath: '/api/ingest/$source'
      preLoaderRoute: typeof ApiIngestSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiIndexerRoute: ApiIndexerRoute,
  ApiProtectRoute: ApiProtectRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiSummarizerRoute: ApiSummarizerRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CChatIdRoute: CChatIdRoute,
  UserSettingsRoute: UserSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIngestSourceRoute: ApiIngestSourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
